<?php 
/**
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
$this->headTitle('Custom Text');
     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/custom.css');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/customtext.js');

$auth = Zend_Auth::getInstance();
$identity = $auth->getIdentity();
$accesslevel = $identity[PeopleDAO::ACCESS_LEVEL];

$this->placeholder('body')->set('class="yui-skin-sam" onload="setAccessLevel(\'' . $accesslevel . '\'); initButtons()"');
?>
<div id="recordinfo">
	<h1 class="recordtitle">Custom Text </h1>
</div>
<div id="customtextcontent">
<div id="demo" class="yui-navset yui-navset-top">
<div class="example">
<div class="customtextinformation">
    <div id="listtype" class="together">
    	<?php echo $this->form->listtypeselect ?>
    </div>

	<div id="customtextlist"></div>

	<div class="formerrors" id="customtexterrors"></div>
	<br style="clear:both"/>
	<div class="shortbuttonfooter" id="customtextbuttons">
		<div class="buttondiv"><input type="button" value="Add New" id="addnewbutton"></div>
		<div class="buttondiv"><input type="button" value="Delete Selected" id="deleteselectedbutton" /></div>
	</div>
</div>
</div>
  </div>
</div>
</div>