<?php 
$title = "";

$auth = Zend_Auth::getInstance();
$identity = $auth->getIdentity();
$accesslevel = $identity[PeopleDAO::ACCESS_LEVEL];
$userid = $identity[PeopleDAO::PERSON_ID];

$tab = RecordNamespace::getRenderTab();
$itemid = 0;
$isbeingedited = 0;
$item = RecordNamespace::getCurrentItem();
if (isset($item))
{
	$itemid = $item->getItemID();
	if (is_null($itemid))
	{
		$itemid = 0;
		$title = "New Record";
	}
	else 
	{
		$title = "Record #" . $itemid;
	}
	if (!$item->isEditable())
	{
		$isbeingedited = 1;
	}
}
else 
{
	$title = "New Record";
}

//If this is a record view, then display the record number as the title
//Otherwise display the action as the title
$request = Zend_Controller_Front::getInstance()->getRequest();
if ($request->getActionName() == "index")
{
	$this->headTitle($title);
}
else 
{
	$this->headTitle($request->getActionName())
     	->headTitle($request->getControllerName());
}

     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/record.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/includes.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/record.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/customelements.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/myrecords.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/transfers.js');

$savestatus = RecordNamespace::getSaveStatus();
RecordNamespace::setSaveStatus(RecordNamespace::SAVE_STATE_IDLE);

$statusmessage = RecordNamespace::getStatusMessage();
RecordNamespace::setStatusMessage(RecordNamespace::DEFAULT_STATUS_MESSAGE);

$this->placeholder('body')->set('class="yui-skin-sam" onload=" initCheckingForModifications(); displaySaveStatus(\'' . $savestatus . '\'); initButtons(\'' . $accesslevel . '\', \'' . $userid . '\', \'' . $itemid . '\', \'' . $isbeingedited . '\'); initTabViewBrowserHistory(\'' . $tab . '\'); loadAutoCompleteTextBoxes(); loadMyRecords();  " onunload="clearEdits()" onbeforeunload="return checkForModifications()"');
?>

<style type="text/css">
#yui-history-iframe {
  position:absolute;
  top:0; left:0;
  width:1px; height:1px; /* avoid scrollbars */
  visibility:hidden;
}

</style>


<!-- Static markup required for browser history management. Note that these
     could be created using document.write in a script block. But they have
     to be created while the page is being parsed, so it cannot be done
     from an imported script file. Also, these have to be created as early
     as possible to avoid problems on Internet Explorer.
     Note that "magic URLs" such as:

         javascript:document.open();document.write(new Date().getTime());document.close();

     and such do NOT work on IE6! Only a real document works (that "real
     document" does not need to be an HTML document. It can be an image
     as well. Using an asset that you use somewhere else on your site,
     instead of a separate asset avoids an unnecessary server round trip.
     Finally, note that the iframe is only used on Internet Explorer.
     If this page is server generated (by a PHP script for example), it is
     a good idea to create the IFrame ONLY for Internet Explorer (use
     server side user agent sniffing) -->
<iframe id="yui-history-iframe" src="<?php echo $this->baseUrl()?>/assets/blank.html"></iframe>
<input id="yui-history-field" type="hidden">


<div id="recordinfo">
	<h1 class="recordtitle"><?php echo $this->placeholder("recordnumber")?></h1>
    <div id="recorddetails"><?php echo $this->placeholder("recordinfo")?></div>
    <div id="statusdiv"><?php echo $statusmessage; ?></div>
</div>
<div id="myrecordsarea">
    <?php  include ("myrecords.phtml"); ?>
</div>
<div id="recordcontent">
<div id="demo" class="yui-navset yui-navset-top">	
  <ul class="yui-nav">
    <li title="active" class="selected"><a href="#tab1"><em>Identification</em></a></li>
    <li title="" class=""><a href="#tab2"><em>Login</em></a></li>
    <li title="" class=""><a href="#tab3"><em>Proposal</em></a></li>
    <li title="" class=""><a href="#tab4"><em>Report</em></a></li>
    <li title="" class=""><a href="#tab5"><em>Logout</em></a></li>
    <li title="" class=""><a href="#tab6"><em>Files</em></a></li>
    <li id="temptransfer" title="" class=""><a href="#tab7"><em>Temp Transfer</em></a></li>
    <li id="temptransferreturn" title="" class=""><a href="#tab8"><em>Temp Transfer Return</em></a></li>
  </ul>
  
  <div class="yui-content">	 
    <div id="tab1"><?php echo $this->form->recordidentificationform ?></div>
    <div id="tab2"><?php echo $this->form->recordloginform ?></div>
    <div id="tab3"><?php echo $this->form->recordproposalform ?></div>
    <div id="tab4"><?php echo $this->form->recordreportform ?></div>
    <div id="tab5"><?php echo $this->form->recordlogoutform ?></div>
    <div id="tab6"><?php echo $this->form->recordfileform ?></div>
    <div id="tab7"><?php echo $this->form->recordtemporarytransferform ?></div>
    <div id="tab8"><?php echo $this->form->recordtemporarytransferreturnform ?></div>
    
    <?php include ("transferlist.phtml"); ?>
  </div>
</div>
<?php echo $this->form->transferdialogform ?>

</div>

