<!--
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 -->
<div class="formerrors"><?php echo $this->placeholder("reporterrormessage")?></div>
<form id="reportform" name="reportform" method="post" action="<?php echo $this->baseUrl()?>/recordreport/savereport" onsubmit="catchSubmit(this)">
<div class="example">
<div class="disabledmessage"><?php echo $this->placeholder("reportdisabledmessage")?></div>
<?php echo $this->element->hiddenreportitemid ?>
	<div id="reportinfo">
<div class="reportcolumn1">
    <div class="together"><?php echo $this->element->reportdateinput ?></div>
    <div class="calendarChooser" id="reportCalendarChooserContainer"></div>
	<div class="together"><?php echo $this->element->reportbyselectform ?></div>
    <div class="together"><?php echo $this->element->worklocationselectform ?></div>
    <div class="together"><?php include ("workdoneby.phtml"); ?></div>
    <div class="together"><?php echo $this->element->workdonebyhidden?></div>
    <div class="together"><?php echo $this->element->formatselectform ?></div>
    
</div>

<div class="reportcolumn2">
	<fieldset id="reportdimensions"><legend>Dimensions</legend>
    	<div id="reportdimsarea">
        <div class="units"><?php echo $this->element->reportunitselect ?></div>
        <div class="reportdimsdiv"><label for="reportheightinput" class="countlabel">Height </label><?php echo $this->element->reportheightinput ?></div>
        <div class="reportdimsdiv"><label for="reportwidthinput" class="countlabel">Width </label><?php echo $this->element->reportwidthinput ?></div>
         <div class="reportdimsdiv"><label for="reportthicknessinput" class="countlabel">Thickness </label><?php echo $this->element->reportthicknessinput ?></div>
         </div>
    </fieldset>
    <div class="together"><?php include ("finalcounts.phtml"); ?></div>
</div>

<div class="reportcolumn3">
	Comments<?php echo $this->element->reportcommentstextarea ?> 
    <div id="reportchecksdiv">
	<?php echo $this->element->adminonlycheckbox ?>
    <br>
    <?php echo $this->element->examonlycheckbox ?>
    <br>
    <?php echo $this->element->customhousingonlycheckbox ?>
    <br>
    <?php echo $this->element->additionalmaterialsonfilecheckbox ?>
    </div>
</div>
</div>


<br style="clear:both;">
<br><br><br/>

<div class="reportcolumn1">
	<?php echo $this->element->reporttreatmentselect ?>
    <br>
    <?php echo $this->element->reporttreatmenttextarea ?>
    
</div>

<div class="reportcolumn2">
	<fieldset><legend>Preservation Recommendations</legend>
    <?php echo $this->element->presrec1select ?><?php echo $this->element->presrec2select ?>
    <br>
    <?php echo $this->element->presrectextarea ?>
    </fieldset>
</div>

<div class="reportcolumn3">
	<div class="together"><?php include ("importance.phtml"); ?></div>
	
<!-- /* per bug 4202    Treatments of Note Summary:<?php echo $this->element->reporttreatmentsummarytextarea ?> */ -->
</div>

<br style="clear:both;">

<div id="reporthoursdiv">
    <?php echo $this->element->actualhours ?>
</div>

	<div class="shortbuttonfooter" id="reportsummarybuttons">
		<input type="button" value="Email Report" id="emailreportbutton">
    	<input type="button" value="View Report Summary" id="viewreportsummarybutton">
	</div>

	<div class="shortbuttonfooter" id="reportbuttons">
    <input type="button" value="Save" id="savereportbutton">
    <input type="button" value="Clear Changes" id="clearreportbutton">
    </div>

</div>
</form>

<?php 
$item = RecordNamespace::getCurrentItem();
if (!isset($item) || is_null($item))
{
	echo "<script type=\"text/javascript\">document.getElementById('reportbuttons').style.display = 'none'; document.getElementById('reportsummarybuttons').style.display = 'none'</script>";
}
else 
{
	$disabledmessage = $item->getDisableReportMessage();
	if (empty($disabledmessage))
	{
		echo "<script type=\"text/javascript\">document.getElementById('reportbuttons').style.display = 'block'</script>";
	}
	else 
	{
		echo "<script type=\"text/javascript\">document.getElementById('reportbuttons').style.display = 'none'</script>";
	}
	if (is_null($item->getFunctions()->getReport()->getPrimaryKey()))
	{
		echo "<script type=\"text/javascript\">document.getElementById('reportsummarybuttons').style.display = 'none'</script>";
	}
}
?>
