<?php 
/**
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
$request = Zend_Controller_Front::getInstance()->getRequest();
$this->headTitle("Record Not Member of Your Repository");

$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/errors.css');

$this->placeholder('body')->set('class="yui-skin-sam"');
?>
<div id="recordinfo">
	<h1 class="recordtitle">Record Not Member of Your Repository</h1>
</div>
<div id="notinrepositorycontent">

<div id="demo" class="yui-navset yui-navset-top">
  <form id="notinrepositoryform" name="notinrepositoryform" method="get" action="<?php echo $this->baseUrl()?>/user/index">
<div class="example">
<div class="notinrepositoryinformation">
 <div id="notinrepositorymessage">
 	<?php echo $this->placeholder("recordnumberlabel")?> is not part of your repository.  Please contact the ACORN administrator if you must have rights to view this record.
</div>
	 <div id="notinrepositorybuttondiv" class="notinrepositorybuttondiv"><input type="button" value="OK" id="notinrepositorybutton" /></div>
 
</div>
</div>
</form>
  </div>
</div>

<script type="text/javascript">
function onButtonReady() {

	//Makes the buttons YUI widgets for a nicer look.
	var oButton = new YAHOO.widget.Button("notinrepositorybutton", {type: "submit"});
}

YAHOO.util.Event.onContentReady("notinrepositorybutton", onButtonReady);
</script>