<!--
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 -->
<div class="formerrors"><?php echo $this->placeholder("temptransferreturnerrormessage")?></div>
<form id="recordtemporarytransferreturnform" name="recordtemporarytransferreturnform" method="post" action="<?php echo $this->baseUrl()?>/record/addtotransferlist" onsubmit="catchSubmit(this)">
<div class="example">
<?php echo $this->element->transferlistname ?>
<div class="disabledmessage"><?php echo $this->placeholder("temptransferreturndisabledmessage")?></div>

<?php echo $this->element->hiddentemptransferreturnitemid ?>
<div class="logininformation">
	<div class="together"><?php echo $this->element->transferreturndateinput ?></div>
    <div class="calendarChooser" id="tempreturnCalendarChooserContainer"></div>
	<div class="together"><?php echo $this->element->transferreturnfromselectform ?></div>
    <div class="together"><?php echo $this->element->transferreturntoselectform ?></div>
    <div class="together"><?php echo $this->element->returncommentstextarea ?></div>
</div>  

<div class="transferbuttonfooter" id="returnbuttons">
    <div class="buttondiv" id="returntransferbuttondiv"><input type="button" value="Add to Return List" id="addtotempreturnlistbutton"></div>
    <div class="buttondiv" id="returndeletebuttondiv"><input type="button" value="Delete Return" id="deletereturnbutton"></div>
</div>

</div>
</form>

<?php 
//Save button is hidden if there is a disable logout message
$hideSaveButton = FALSE;
$hideDeleteButton = FALSE;
$item = RecordNamespace::getCurrentItem();
if (isset($item) && !is_null($item))
{
	$disabledmessage = $item->getDisableTempTransferReturnMessage();
	if (!empty($disabledmessage))
	{
		$hideSaveButton = TRUE;
		//If the item is not transferred out in, also disable the delete
		//or if the item doesn't have a return
		if (is_null($item->getFunctions()->getTemporaryTransfer()->getPrimaryKey())
		|| is_null($item->getFunctions()->getTemporaryTransferReturn()->getPrimaryKey()))
		{
			$hideDeleteButton = TRUE;
		}
	}
}

if ($hideSaveButton)
{
	echo "<script type=\"text/javascript\">document.getElementById('returntransferbuttondiv').style.display = 'none'</script>";
}
if ($hideDeleteButton)
{
	echo "<script type=\"text/javascript\">document.getElementById('returndeletebuttondiv').style.display = 'none'</script>";
}
?>