<!--
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 -->
<div id="transferdialog">
	<div class="hd">Please enter the transfer information</div>
	<div class="bd">
		<form method="POST" action="<?php echo $this->baseUrl()?>/reports/<?php echo $this->element->getAction()?>">
			<div id="courierautocomplete" class="together">
			<?php echo $this->element->courierinput?>
	        <br>
			<div id="couriercontainer"></div>
			<div id="courier2autocomplete" class="together">
			<?php echo $this->element->courier2input?>
	        <br>
			<div id="courier2container"></div>
			<div class="together"><?php echo $this->element->transportcontainertextarea ?></div>
		</form>
	</div>
</div>
