<script type="text/javascript" 
src="http://yui.yahooapis.com/combo?2.8.2r1/build/yahoo-dom-event/yahoo-dom-event.js
&2.8.2r1/build/yuiloader-dom-event/yuiloader-dom-event.js
&2.8.2r1/build/event/event-min.js
&2.8.2r1/build/element/element-min.js
&2.8.2r1/build/paginator/paginator-min.js
&2.8.2r1/build/dragdrop/dragdrop-min.js
&2.8.2r1/build/container/container-min.js
&2.8.2r1/build/tabview/tabview-min.js
&2.8.2r1/build/history/history-min.js
&2.8.2r1/build/menu/menu-min.js
&2.8.2r1/build/connection/connection-min.js
&2.8.2r1/build/button/button-min.js
&2.8.2r1/build/datasource/datasource-min.js
&2.8.2r1/build/datatable/datatable-min.js
&2.8.2r1/build/autocomplete/autocomplete-min.js
&2.8.2r1/build/animation/animation-min.js
&2.8.2r1/build/json/json-min.js
&2.8.2r1/build/calendar/calendar-min.js
&2.8.2r1/build/uploader/uploader-min.js"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/json.js" ></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/prototype.js" ></script> 
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/scripts/acorn.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/checkModifications.js" ></script>
