<!--
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 -->
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/yui-2.8.2r1.js" ></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/json.js" ></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/prototype.js" ></script> 
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/scripts/acorn.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/checkModifications.js" ></script>
