<script type="text/javascript" 
src="http://yui.yahooapis.com/combo?2.7.0/build/yahoo-dom-event/yahoo-dom-event.js
&2.7.0/build/element/element-min.js
&2.7.0/build/paginator/paginator-debug.js
&2.7.0/build/dragdrop/dragdrop-debug.js
&2.7.0/build/container/container-debug.js
&2.7.0/build/tabview/tabview-debug.js
&2.7.0/build/history/history-debug.js
&2.7.0/build/menu/menu-debug.js
&2.7.0/build/connection/connection-debug.js
&2.7.0/build/button/button-debug.js
&2.7.0/build/datasource/datasource-debug.js
&2.7.0/build/datatable/datatable-debug.js
&2.7.0/build/autocomplete/autocomplete-debug.js
&2.7.0/build/animation/animation-debug.js
&2.7.0/build/event/event-debug.js
&2.7.0/build/json/json-debug.js
&2.7.0/build/calendar/calendar-debug.js
&2.8.1/build/uploader/uploader-debug.js"></script>

<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/json.js" ></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/prototype.js" ></script> 
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/scripts/acorn.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/checkModifications.js" ></script>
