<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/yui-2.9.0.js" ></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/json.js" ></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/prototype.js" ></script> 
<script type="text/javascript" src="<?php echo $this->baseUrl()?>/scripts/acorn.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/scripts/checkModifications.js" ></script>
