<?php 
/**
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
$title = "";

$itemid = 0;
$item = RecordNamespace::getCurrentItem();
if (isset($item))
{
	$itemid = $item->getItemID();
	$title = "Email - Record #" . $itemid;
}
else 
{
	$title = "Email";
}
$this->headTitle($title);
     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/proposalapproval.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/proposalapproval.js');

$this->placeholder('body')->set('class="yui-skin-sam" onload="initEmailButtons()"');
?>
<div id="recordinfo">
    <h1 class="recordtitle"><?php echo $title?> </h1>
</div>
<div id="demo">   
<div class="formerrors"><?php echo $this->placeholder("emailerrormessage")?></div>
<form id="emailform" name="emailform" action="<?php echo $this->baseUrl()?>/proposalapproval/sendemail" method="post">
<div id="emailcontent">
	<div id="emaildata">
    	<div class="together"><?php echo $this->form->toinput ?></div>
		<div class="together"><?php echo $this->form->ccinput ?></div>
		<div class="together"><?php echo $this->form->subjectinput ?></div>
		<div class="together"><?php echo $this->form->messageinput ?></div>
		<div id="emailbuttons">
			<input type="button" value="Email" id="emailbutton">
        	<input type="button" value="Cancel" id="cancelbutton">
        </div>
    </div>
    <div class="together"><?php echo $this->form->hiddenactivity ?></div>
    <div class="together"><?php echo $this->form->hiddendetails ?></div>
    <div class="together"><?php echo $this->form->hiddenemailtype ?></div>
</div>
</form>
</div>



