<?php 
$title = "";

$itemid = 0;
$item = RecordNamespace::getCurrentItem();
$isreadonly = 1;
$isloggedin = 0;

if (isset($item))
{
	if (Zend_Auth::getInstance()->hasIdentity())
	{
		$isloggedin = 1;
		$identity = Zend_Auth::getInstance()->getIdentity();
		$itemid = $item->getItemID();
		$title = "Proposal Approval - Record #" . $itemid;
		if ($item->getCuratorID() == $identity[PeopleDAO::PERSON_ID])
		{
			$isreadonly = 0;
		}
	}
	elseif (!isset($this->readonly) || $this->readonly == 0)
	{
		//Assuming the curator is the person viewing the record if no one is logged in.
		$isreadonly = 0;
	}
}
else 
{
	$title = "Proposal Approval";
}

$savestatus = RecordNamespace::getSaveStatus();
RecordNamespace::setSaveStatus(RecordNamespace::SAVE_STATE_IDLE);

$this->headTitle($title);
  
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/proposalapproval.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/proposalapproval.js');

$this->placeholder('body')->set('class="yui-skin-sam" onload="displaySaveStatus(\'' . $savestatus . '\'); initButtons(\'' . $itemid . '\', ' . $isreadonly . ', ' . $isloggedin . '); initTabViewBrowserHistory(); initCheckingForModifications();" onunload="clearEdits()" onbeforeunload="return checkForModifications()"');
?>

<style type="text/css">
#yui-history-iframe {
  position:absolute;
  top:0; left:0;
  width:1px; height:1px; /* avoid scrollbars */
  visibility:hidden;
}

</style>


<!-- Static markup required for browser history management. Note that these
     could be created using document.write in a script block. But they have
     to be created while the page is being parsed, so it cannot be done
     from an imported script file. Also, these have to be created as early
     as possible to avoid problems on Internet Explorer.
     Note that "magic URLs" such as:

         javascript:document.open();document.write(new Date().getTime());document.close();

     and such do NOT work on IE6! Only a real document works (that "real
     document" does not need to be an HTML document. It can be an image
     as well. Using an asset that you use somewhere else on your site,
     instead of a separate asset avoids an unnecessary server round trip.
     Finally, note that the iframe is only used on Internet Explorer.
     If this page is server generated (by a PHP script for example), it is
     a good idea to create the IFrame ONLY for Internet Explorer (use
     server side user agent sniffing) -->
<iframe id="yui-history-iframe" src="<?php echo $this->baseUrl()?>/assets/blank.html"></iframe>
<input id="yui-history-field" type="hidden">


<div id="recordinfo">
	<h1 class="recordtitle"><?php echo $this->placeholder("recordnumber")?></h1>
    <div id="recorddetails"><?php echo $this->placeholder("recordinfo")?></div>
    <div id="statusdiv">Your comment has been saved!</div>
</div>
<div id="approvalcontent">
<?php if (!empty($itemid)) {?>
<div id="returntorecorddiv"><a href="<?php echo $this->baseUrl();?>/record/index/recordnumber/<?php echo $itemid;?>">Return to Record</a></div>
<?php }?>
<div id="demo" class="yui-navset yui-navset-top">	
  <ul class="yui-nav">
    <li title="active" class="selected"><a href="#tab1"><em>Proposal Approval</em></a></li>
    <li title="" class=""><a href="#tab2"><em>History</em></a></li>
    <?php if (!is_null($item->getFunctions()->getReport()->getPrimaryKey()))
    {?>
    <li title="" class=""><a href="#tab3"><em>Final Report Summary</em></a></li>
    <li title="" class=""><a href="#tab4"><em>Files</em></a></li>
    <?php }
    else {?>
    <li title="" class=""><a href="#tab3"><em>Files</em></a></li>
    <?php }?>
  </ul>
  
  <div class="yui-content">	 
    <div id="tab1"><?php echo $this->form->proposalsummaryform ?></div>
    <div id="tab2"><?php echo $this->form->historyform ?></div>
    <?php if (!is_null($item->getFunctions()->getReport()->getPrimaryKey()))
    {?>
    <div id="tab3"><?php echo $this->form->reportsummaryform ?></div> 
    <div id="tab4"><?php echo $this->form->recordfileform ?></div>
    <?php }
    else {?>  
    <div id="tab3"><?php echo $this->form->recordfileform ?></div>
    <?php }?>
  </div>
</div>

</div>

