<!--
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 -->
<div class="formerrors"><?php echo $this->placeholder("historyerrormessage")?></div>
<form id="historyform" name="historyform" method="post" action="<?php echo $this->baseUrl()?>/proposalapproval/savecomment#tabview=tab1" onsubmit="catchSubmit(this)">
<div class="example">
<div id="historydiv">
</div>
<div id="historycommentscolumn">
	<div class="together"><?php echo $this->element->historycommentstextarea ?></div>
</div>

<div id="historybuttoncolumn">
	<div class="contactarea">
		<div class="together" id="historyauthordiv"><?php echo $this->element->historyauthorselect ?></div>
		<div class="together"><?php echo $this->element->historytoinput ?></div>
		<div class="together"><?php echo $this->element->historyccinput ?></div>
	</div>
	<div id="historybuttons">
		<input type="button" value="Add Comment" id="commentbutton">
	</div>
</div>

</div>
</form>
<?php 
$item = RecordNamespace::getCurrentItem();
if (!isset($item) || is_null($item))
{
	echo "<script type=\"text/javascript\">document.getElementById('historybuttons').style.display = 'none';</script>";
}
else 
{
	echo "<script type=\"text/javascript\">document.getElementById('historybuttons').style.display = 'block'</script>";
}
?>
