<div class="formerrors"><?php echo $this->placeholder("reportsummaryerrormessage")?></div>
<div class="example">
<div class="disabledmessage"><?php echo $this->placeholder("reportdisabledmessage")?></div>
<div id="printreportbuttondiv"><input type="button" value="Print Report" id="printreportbutton"></div>
<div id="reportsummarydiv">
	<div class="left">
		<div class="together"><div class="titleheaders">Repository:</div><div class="data"> <?php echo $this->placeholder("reportrepository");?></div></div>
		<div class="together"><div class="titleheaders">Curator:</div><div class="data"> <?php echo $this->placeholder("reportcurator");?></div></div>
		<div class="together"><div class="titleheaders">Project:</div><div class="data"> <?php echo $this->placeholder("reportproject");?></div></div>
		<div class="together"><div class="titleheaders">Group:</div><div class="data"> <?php echo $this->placeholder("reportgroup");?></div></div>
		<div class="together"><div class="titleheaders">Coordinator:</div><div class="data"> <?php echo $this->placeholder("reportcoordinator");?></div></div>
		<div class="together"><div class="titleheaders">Item Counts:</div><div class="data"> <?php echo $this->placeholder("reportcounts");?></div></div>
	</div>
	
	<div class="right">
		<div class="together"><div class="titleheaders">Call Numbers:</div><div class="data"> <?php echo $this->placeholder("reportcallnumbers");?></div></div>
		<div class="together"><div class="titleheaders">Author/Artist:</div><div class="data"> <?php echo $this->placeholder("reportauthor");?></div></div>
		<div class="together"><div class="titleheaders">Title:</div><div class="data"> <?php echo $this->placeholder("reportitemtitle");?></div></div>
		<div class="together"><div class="titleheaders">Date of Object:</div><div class="data"> <?php echo $this->placeholder("reportdateofobject");?></div></div>
		<div class="together"><div class="titleheaders">Size:</div><div class="data"> <?php echo $this->placeholder("reportsize");?></div></div>
	</div>
	
	<br style="clear: both"/>
	<div class="together"><div class="singlecolumnheaders">Comments:</div><div class="singlecolumndata"> <?php echo $this->placeholder("reportcomments");?><br/><br/></div></div>
	<div class="together"><div class="singlecolumnheaders">Comments:</div><div class="singlecolumndata"> <?php echo $this->placeholder("preservationrecommendations");?><br/><br/></div></div>
	<div class="together"><div class="singlecolumnheaders">Treatment Performed:</div><div class="singlecolumndata"> <?php echo $this->placeholder("reporttreatment");?><br/><br/></div></div>
</div>


<div id="completedhoursdiv"><?php echo $this->placeholder("completedhours");?></div>

</div>
