<?php 
/**
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
$this->headTitle('User Login');
     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/userlogin.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/customelements.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/userlogin.js');

$this->placeholder('body')->set('class="yui-skin-sam" onload="initButtons(); loadRepositoryValues(); initContent()"');
?>

<form id="userloginform" name="userloginform" action="<?php echo $this->baseUrl()?>/index/process" method="post">
<div id="userlogincontent">
	<img alt="ACORN Title" src="/images/AcornTitle.jpg" border="0">
    <div id="recordinfo">
        <h1 class="recordtitle">Please Login </h1>
    </div>
    <div id="userlogindata">
    	<? echo $this->form ?>
        <div class="together"><?php echo $this->form->usernameinput ?></div>
		<div class="together"><?php echo $this->form->passwordinput ?></div>
		<div class="together"><?php echo $this->form->accesslevelselectform ?></div>
		<div class="shortbuttonfooter">
			<?php echo $this->form->userloginbutton ?>
        </div>
    </div>
</div>
</form>


