<!--
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 -->
<div class="formerrors"><?php echo $this->placeholder("proposalerrormessage")?></div>
<h1 class="functiontitle" align="center">Proposal</h1>

<form id="groupproposalform" name="groupproposalform" method="post" action="<?php echo $this->baseUrl() ?>/groupproposal/updaterecords">
<div class="example">
<div class="disabledmessage"><?php echo $this->placeholder("proposaldisabledmessage")?></div>
<div class="proposalcolumn1">
	<div class="together"><?php echo $this->element->proposalcommentstextarea ?></div>
</div>

<div class="proposalcolumn2">
	<div class="together"><?php echo $this->element->proposaldateinput ?></div>
    <div class="calendarChooser" id="proposalCalendarChooserContainer"></div>
	<div class="together"><?php include ("proposedby.phtml"); ?></div>
    <div class="together"><?php echo $this->element->proposalbyhidden?></div>
    <div class="together"><?php echo $this->element->examdateinput ?></div>
    <div class="calendarChooser" id="examCalendarChooserContainer"></div>
	<div class="together"><?php echo $this->element->examlocationselectform ?></div>
</div>

<div class="proposaldimensionscolumn">
	<fieldset id="fielddimensions"><legend>Dimensions</legend>
    	<div id="proposaldims">
        	<div class="units"><?php echo $this->element->unitselect ?></div>
	        <div class="together"><?php echo $this->element->proposalheightinput ?></div>
	        <div class="together"><?php echo $this->element->proposalwidthinput  ?></div>
	        <div class="together"><?php echo $this->element->proposalthicknessinput ?></div>
        </div>
    </fieldset>
</div>

<br style="clear:both;">
<br>

<div class="column1">
	<div class="together"><?php echo $this->element->proposaldescriptionselect ?></div>
    <?php echo $this->element->proposaldescriptiontextarea ?>
</div>

<div class="column2">
	<div class="together"><?php echo $this->element->proposalconditionselect ?></div>
    <?php echo $this->element->proposalconditiontextarea ?>
</div>

<div class="column3">
	<div class="together"><?php echo $this->element->proposaltreatmentselect ?></div>
    <?php echo $this->element->proposaltreatmenttextarea ?>
</div>

<br style="clear:both;">

<div id="proposedhoursdiv">
    <div class="together"><?php echo $this->element->proposedhoursmin ?> to <?php echo $this->element->proposedhoursmax?></div>
</div>

<div class="shortbuttonfooter" id="proposalbuttons">
	<input type="button" value="Save to All Records" id="saveproposalbutton">
    <input type="button" value="Clear Changes" id="clearproposalbutton">
</div>

</div>
</form>

<?php 
$group = GroupNamespace::getCurrentGroup();
if (!isset($group) || is_null($group))
{
	echo "<script type=\"text/javascript\">document.getElementById('proposalbuttons').style.display = 'none';</script>";
}
else 
{
	$disabledmessage = $group->getDisableProposalMessage();
	if (empty($disabledmessage))
	{
		echo "<script type=\"text/javascript\">document.getElementById('proposalbuttons').style.display = 'block'</script>";
	}
	else 
	{
		echo "<script type=\"text/javascript\">document.getElementById('proposalbuttons').style.display = 'none'</script>";
	}
}
?>