<!--
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 -->
<div class="formerrors"><?php echo $this->placeholder("temptransfererrormessage")?></div>
<h1 class="functiontitle" align="center">Temporary Transfer</h1>

<form id="grouptemporarytransferform" name="grouptemporarytransferform" method="post" action="<?php echo $this->baseUrl()?>/group/addtotransferlist">
<div class="example">
<?php echo $this->element->transferlistname ?>
<?php echo $this->element->transferids6 ?>
<div class="disabledmessage"><?php echo $this->placeholder("temptransferdisabledmessage")?></div>
<div class="logininformation">
	<div class="together"><?php echo $this->element->transferdateinput ?></div>
    <div class="calendarChooser" id="temptransferCalendarChooserContainer"></div>
	<div class="together"><?php echo $this->element->transferfromselectform ?></div>
    <div class="together"><?php echo $this->element->transfertoselectform ?></div>
	<div class="together"><?php echo $this->element->temptransfercommentstextarea ?></div>
</div>  
</div>
</form>