<!--
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 -->
<div class="formerrors"><?php echo $this->placeholder("logouterrormessage")?></div>
<h1 class="functiontitle" align="center">Group Logout</h1>

<form id="grouplogoutform" name="grouplogoutform" method="post" action="<?php echo $this->baseUrl()?>/grouplogout/savelogout">
<div class="example">
<?php echo $this->element->transferlistname ?>
<?php echo $this->element->transferids4 ?>
<div class="disabledmessage"><?php echo $this->placeholder("logoutdisabledmessage")?></div>
<div class="logininformation">
	<div class="together"><?php echo $this->element->logoutdateinput ?></div>
	<div class="calendarChooser" id="logoutCalendarChooserContainer"></div>
	<div class="together"><?php echo $this->element->logoutbyselectform ?></div>
	<div class="together"><?php echo $this->element->logoutfromselectform ?></div>
	<div class="together"><?php echo $this->element->logouttoselectform ?></div>  
</div> 
</div>
</form>