<?php 
/**
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/files.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/groupfile.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/dropzone.js');

$accesslevel = "None";
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity())
{
	$identity = $auth->getIdentity();
	$accesslevel = $identity[PeopleDAO::ACCESS_LEVEL];
}
?>
<div class="formerrors"><?php echo $this->placeholder("fileserrormessage")?></div>
<div class="disabledmessage"><?php echo $this->placeholder("filesdisabledmessage")?></div>
<?php echo $this->element->hiddenfilepkid ?>
<div class="together">
	<?php echo $this->element->filesearchinput?>
</div>
<div id="files"></div>

<?php if ($accesslevel == PeopleDAO::ACCESS_LEVEL_ADMIN || $accesslevel == PeopleDAO::ACCESS_LEVEL_REGULAR) {?>
<article itemscope itemtype="http://schema.org/WebApplication">
<div id="dropzone"><form action="<?php $this->baseUrl(); ?>/groupfiles/addnewfile" class="dropzone" id="group-file-upload">
</form></div>
</article>

<div class="fullbuttonfooter" id="filebuttons">
	<input type="button" value="Upload File" id="fileuploadbutton">
</div>

<?php }?>

<script type="text/javascript">
document.getElementById('filebuttons').style.display = 'none';
var files = 0;
Dropzone.options.groupFileUpload = {
		paramName: "file", // The name that will be used to transfer the file
		  addRemoveLinks: true,
		  init: function() {
			this.on("processing", function(file)
				{
					//When a file is being processed, don't allow it to be displayed
					document.getElementById('filebuttons').style.display = 'none';
				});
		    this.on("success", function(file, retval) { 
			    if (files > 0)
			    {
		    		document.getElementById('filebuttons').style.display = 'block';
			    }
			 });
		    this.on("error", function(file, message) { alert(message); });
		    this.on("removedfile", function(file) {
		    	removeFileFromTempDirectory(file["name"]);
		    	files--;
			    if (files == 0)
			    {
			    	document.getElementById('filebuttons').style.display = 'none';
			    }
			    });
		    this.on("addedfile", function(file) {
			    files++;
			    });
		    this.on("canceled", function(file) {
		    	files--;
			    if (files == 0)
			    {
			    	document.getElementById('filebuttons').style.display = 'none';
			    }
			    });
		    
		  }
		};

</script>


