#!/bin/bash
ACORNINSTANCE='dev'
ACORNURL='localhost:8443'
ACORNMAILTO='acornadm@localhost.local'
ACORNDATABASENAME='acorndb1'
ACORNMAKEDB='y'
ACORNMAKEUSER='y'
ACORNLOADTABLES='y'
ACORNMYSQLPASS='acorndbpass1'
MYSQLADMINPW='docrootpw1'
export ACORNINSTANCE ACORNURL ACORNMAILTO ACORNDATABASENAME ACORNMAKEDB ACORNLOADTABLES ACORNMAKEUSER ACORNMYSQLPASS MYSQLADMINPW
