<?php 
/**
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
$request = Zend_Controller_Front::getInstance()->getRequest();
$this->headTitle($request->getActionName())
     ->headTitle($request->getControllerName());
     
/* Combo-handled YUI CSS files: */
//$this->headLink()->appendStylesheet('http://yui.yahooapis.com/combo?2.7.0/build/reset-fonts-grids/reset-fonts-grids.css&2.7.0/build/menu/assets/skins/sam/menu.css');
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/recordsearch.css');

/* Combo-handled YUI JS files: */
//$this->headScript()->appendFile($this->baseUrl() . '/scripts/recordstatus.js');
//$this->headScript()->appendFile('http://yui.yahooapis.com/combo?2.7.0/build/yahoo-dom-event/yahoo-dom-event.js&2.7.0/build/container/container_core-min.js&2.7.0/build/menu/menu-min.js');

$this->placeholder('body')->set('class="yui-skin-sam"');
?>
<div id="recordinfo">
	<h1 class="recordtitle">Column Chooser Error </h1>
</div>
<div id="fallbackcontent">

<!-- Static markup required for the TabView widget. -->

<div id="demo" class="yui-navset yui-navset-top">
<div class="example">
<div id="fallbackmessage">
	An error occurred when attempting to load the column chooser.<br>
	Please notify the ACORN administrator of this error. <br>
	Press back to continue.  
</div>
</div>

</div>
</div>
