<?php 
$this->headTitle('Saved Searches');
     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/custom.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/savedsearches.js');

$auth = Zend_Auth::getInstance();
$identity = $auth->getIdentity();
$accesslevel = $identity[PeopleDAO::ACCESS_LEVEL];

$this->placeholder('body')->set('class="yui-skin-sam" onload="setAccessLevel(\'' . $accesslevel . '\'); initButtons(); loadSavedSearches();"');
?>
<div id="recordinfo">
	<h1 class="recordtitle">Saved Searches</h1>
</div>
<div id="savedsearchcontent">

<div id="demo" class="yui-navset yui-navset-top">
<div class="example">
<div class="savedsearchinformation">
<div class="formerrors" id="searcherrors"></div>
<div id="savedsearchlist"></div>

<div class="savedsearchbuttonfooter" id="savedsearchbutton"><input type="button" value="Delete Selected" id="deleteselectedbutton" /></div>
</div>
</div>
  </div>
</div>

