<?php 
$this->headTitle('Group Search');
     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/recordsearch.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/customelements.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/search.js');

$this->placeholder('body')->set('class="yui-skin-sam" onload="initGroupSearchButtons()"');
?>
<div id="recordinfo">
	<h1 class="recordtitle">Group Search </h1>
</div>

<div id="searchcontent">

<div id="demo" class="yui-navset yui-navset-top">
  <form id="groupsearchform" name="groupsearchform" method="get" action="<?php echo $this->baseUrl()?>/search/findgroup">
<div class="example">
<div id="searchgroupinformation">
	<div id="recsearch" class="together"><?php echo $this->form->groupselectform ?><input type="button" value="Find Group" id="searchgroupbutton" ></div>     
</div>
</div>
</form>
  </div>
</div>

