<?php 
/**
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
$this->headTitle('Group Search');
     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/recordsearch.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/customelements.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/search.js');

$this->placeholder('body')->set('class="yui-skin-sam" onload="initGroupSearchButtons()"');
?>
<div id="recordinfo">
	<h1 class="recordtitle">Group Search </h1>
</div>

<div id="searchcontent">

<div id="demo" class="yui-navset yui-navset-top">
  <form id="groupsearchform" name="groupsearchform" method="get" action="<?php echo $this->baseUrl()?>/search/findgroup">
<div class="example">
<div id="searchgroupinformation">
	<div id="recsearch" class="together"><?php echo $this->form->groupselectform ?><input type="button" value="Find Group" id="searchgroupbutton" ></div>     
</div>
</div>
</form>
  </div>
</div>

