<?php 
/**
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
$this->headTitle("Change Password");
     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/user.css');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/userlogin.js');

$savestatus = PeopleNamespace::getSaveStatus();
PeopleNamespace::setSaveStatus(PeopleNamespace::SAVE_STATE_IDLE);

$this->placeholder('body')->set('class="yui-skin-sam" onload="displaySaveStatus(\'' . $savestatus . '\'); initChangePasswordButton();"');
?>
<div id="recordinfo">
	<h1 class="recordtitle">Change Password </h1>
    <div id="statusdiv">Password Change Successful!</div>
</div>
<div id="personprofilecontent">
<div id="demo" class="yui-navset yui-navset-top">
<form id="changepasswordform" name="changepasswordform" method="post" action="<?php echo $this->baseUrl()?>/user/savepasswordchange">
<div class="formerrors"><?php echo $this->placeholder("passworderrormessage")?></div>
<div class="example">
<div class="personprofileinformation">
	<div id="passwordinformation">
    <fieldset><legend>Password Change</legend>
    	<div class="together"><?php echo $this->form->oldpassword ?></div>
    	<div class="together"><?php echo $this->form->newpassword ?></div>
        <div class="together"><?php echo $this->form->newpasswordconfirm ?></div>
        <div class="personbuttonfooter" id="changepassworddiv">
        	<input type="button" value="Save New Password" id="savepasswordbutton">
        </div>
        </fieldset>
    </div>

</div>
</div>
</form>
  </div>
</div>
