<?php 
/**
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
$this->headTitle("My Records");
     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/userlogin.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/homepage.js');

$functionname = "loadMyRecordList()";
$identity = Zend_Auth::getInstance()->getIdentity();
if ($identity[PeopleDAO::ACCESS_LEVEL] == PeopleDAO::ACCESS_LEVEL_CURATOR)
{
	$functionname = "loadCuratorRecordList()";
}

$this->placeholder('body')->set('class="yui-skin-sam" onload="' . $functionname . '"');
?>


<div id="userhomepagecontent">
    <img alt="ACORN Title" src="/images/AcornTitle.jpg" border="0">
    <div id="recordinfo">
        <h1 class="recordtitle">My Records </h1>
    </div>
    <div id="userhomepagedata">
    	<div id="myrecordlist"></div>
    </div>
</div>


