<?php 
$this->headTitle("My Records");
     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/userlogin.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/homepage.js');

$functionname = "loadMyRecordList()";
$identity = Zend_Auth::getInstance()->getIdentity();
if ($identity[PeopleDAO::ACCESS_LEVEL] == PeopleDAO::ACCESS_LEVEL_CURATOR)
{
	$functionname = "loadCuratorRecordList()";
}

$this->placeholder('body')->set('class="yui-skin-sam" onload="' . $functionname . '"');
?>


<div id="userhomepagecontent">
    <img alt="ACORN Title" src="/images/AcornTitle.jpg" border="0">
    <div id="recordinfo">
        <h1 class="recordtitle">My Records </h1>
    </div>
    <div id="userhomepagedata">
    	<div id="myrecordlist"></div>
    </div>
</div>


