<?php 
/**
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
$person = PeopleNamespace::getCurrentPerson();
if (isset($person))
{
	$personid = $person->getPrimaryKey();
	if (is_null($personid))
	{
		$title = "New Person";
	}
	else 
	{
		$title = "Edit Person: " . $person->getDisplayName();
	}
}
else 
{
	$title = "New Person";
}

$savestatus = PeopleNamespace::getSaveStatus();
PeopleNamespace::setSaveStatus(PeopleNamespace::SAVE_STATE_IDLE);

$this->headTitle($title);
     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/user.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/userperson.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/customelements.js');

$this->placeholder('body')->set('class="yui-skin-sam" onload="displaySaveStatus(\'' . $savestatus . '\'); initContent(); initButtons(); preparePersonInput();"');
?>
<div id="recordinfo">
	<h1 class="recordtitle">Add or Edit Person </h1>
    <div id="statusdiv">Save Successful!</div>
</div>
<div id="personprofilecontent">
<div id="demo" class="yui-navset yui-navset-top">
<div class="formerrors"><?php echo $this->placeholder("personerrormessage")?></div>
<div class="example">
<div class="personprofileinformation">
	<form id="personprofileform" name="personprofileform" method="post" action="<?php echo $this->baseUrl()?>/people/saveperson">
    <div id="editornewarea">
    	<div id="personautocomplete" class="together">
		<?php echo $this->form->personinput?>
        <br>
		<div id="personcontainer"></div>
        </div>
        <div id="newperson">OR  <input type="button" value="Add New" id="createnewbutton"></div>
	</div>

	<br style="clear: both"/>
	
   	<div id="personinformation">
    	<div class="together"><?php echo $this->form->personidinput?></div>
    	<div id="personname"><?php echo $this->placeholder('personname')?></div>
    	<fieldset><legend>Information</legend>
    	<div class="together" id="inactivediv"><?php echo $this->form->inactivecheckbox?></div>
        <div class="together"><?php echo $this->form->firstnameinput?></div>
        <div class="together"><?php echo $this->form->middlenameinput?></div>
        <div class="together"><?php echo $this->form->lastnameinput?></div>
        <div class="together"><?php echo $this->form->initialsinput?></div>
        <div class="together"><?php echo $this->form->emailinput?></div><br/>
        <div class="together"><?php echo $this->form->logininput?></div>
        <div class="together"><?php echo $this->form->accesslevelselectform?></div>
        <div id="roletypearea"></div>
        <div class="personbuttonfooter">
        <input type="button" value="Save Profile" id="saveprofilebutton">
        <input type="button" value="Clear Changes" id="clearchangesbutton">
        </div>
        </fieldset>
    </div>
    </form>
    
    <br style="clear: both"/>
    <form id="passwordresetform" name="passwordresetform" method="post" action="<?php echo $this->baseUrl()?>/people/resetpassword">
    <div id="passwordinformation">
    <fieldset><legend>Reset Password</legend>
    	<div class="together"><?php echo $this->form->newpassword?></div>
        <div class="together"><?php echo $this->form->newpasswordconfirm?></div>
        <div class="personbuttonfooter">
        	<input type="button" value="Save Password Reset" id="savepasswordbutton">
        </div>
        </fieldset>
    </div>
    </form>

</div>
</div>

  </div>
</div>
</div>


