<?php 
$request = Zend_Controller_Front::getInstance()->getRequest();
$this->headTitle($request->getActionName())
     ->headTitle($request->getControllerName());
     
/* Combo-handled YUI CSS files: */
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/bulk.css');

/* Combo-handled YUI JS files: */
$this->headScript()->appendFile($this->baseUrl() . '/scripts/bulktransfers.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/customelements.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/myrecords.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/transfers.js');

$savestatus = TransferNamespace::getSaveStatus();
TransferNamespace::setSaveStatus(TransferNamespace::SAVE_STATE_IDLE);

$this->placeholder('body')->set('class="yui-skin-sam" onload="displaySaveStatus(\'' . $savestatus . '\'); initLogout(); loadMyRecords(); "');
?>
<div id="recordinfo">
	<h1 class="recordtitle">Bulk Logout </h1>
	<div id="statusdiv">Your records have been saved!</div>
</div>
<div id="myrecordsarea">
    <?php include ("myrecords.phtml"); ?>
</div>
<div id="bulklogoutcontent">

<!-- Static markup required for the TabView widget. -->

<div id="demo" class="yui-navset yui-navset-top">
<form id="bulklogoutform" name="bulklogoutform" method="post" action="../record.php">
<div class="formerrors"><?php echo $this->placeholder("errormessage")?></div>
<div class="example">
<?php echo $this->form->transferlistname ?>
<?php echo $this->form->transferids ?>
<div class="logininformation">
	<div class="together"><?php echo $this->form->logoutdateinput ?></div>
	<div class="calendarChooser" id="logoutCalendarChooserContainer"></div>
	<div class="together"><?php echo $this->form->logoutbyselectform ?></div>
	<div class="together"><?php echo $this->form->logoutfromselectform ?></div>
	<div class="together"><?php echo $this->form->logouttoselectform ?></div>  
</div>  
	<?php include ("matchingbulktransferrecords.phtml"); ?>
	<div class="fullbuttonfooter" id="logoutbuttons">
    <input type="button" value="Add to Transfer List" id="addtotransferlistbutton">
    <input type="button" value="Save Selected" id="savelogoutbutton">
    </div>
	<?php include ("transferlist.phtml"); ?>
    
</div>
</form>
</div>
<?php echo $this->form->transferdialogform ?>
</div>