<?php 
$request = Zend_Controller_Front::getInstance()->getRequest();
$this->headTitle($request->getActionName())
     ->headTitle($request->getControllerName());
     
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/bulk.css');

$this->headScript()->appendFile($this->baseUrl() . '/scripts/bulktransfers.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/customelements.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/myrecords.js');
$this->headScript()->appendFile($this->baseUrl() . '/scripts/transfers.js');

$savestatus = TransferNamespace::getSaveStatus();
TransferNamespace::setSaveStatus(TransferNamespace::SAVE_STATE_IDLE);

$this->placeholder('body')->set('class="yui-skin-sam" onload="displaySaveStatus(\'' . $savestatus . '\'); initLogin(); loadMyRecords();"');
?>
<div id="recordinfo">
	<h1 class="recordtitle">Bulk Login </h1>
	<div id="statusdiv">Your records have been saved!</div>
</div>
<div id="myrecordsarea">
    <?php include ("myrecords.phtml"); ?>
</div>
<div id="bulklogincontent">

<!-- Static markup required for the TabView widget. -->

<div id="demo" class="yui-navset yui-navset-top">
<form id="bulkloginform" name="bulkloginform" method="post" action="../record.php">
<div class="formerrors"><?php echo $this->placeholder("errormessage")?></div>
<div class="example">
<?php echo $this->form->transferlistname ?>
<?php echo $this->form->transferids ?>
<div class="logininformation">
	<div class="together"><?php echo $this->form->logindateinput ?></div>
	<div class="calendarChooser" id="loginCalendarChooserContainer"></div>
	<div class="together"><?php echo $this->form->loginbyselectform ?></div>
	<div class="together"><?php echo $this->form->loginfromselectform ?></div>
	<div class="together"><?php echo $this->form->logintoselectform ?></div>  
	<div class="together"><?php echo $this->form->repositoryselectform ?></div>  
</div>  
	<?php include ("matchingbulktransferrecords.phtml"); ?>
	<div class="fullbuttonfooter" id="loginbuttons">
    <input type="button" value="Add to Transfer List" id="addtotransferlistbutton">
    <input type="button" value="Save Selected" id="saveloginbutton">
    </div>
	<?php include ("transferlist.phtml"); ?>
    
</div>
</form>
</div>
<?php echo $this->form->transferdialogform ?>
</div>