<?php 
if ($this->last > 0) {?>
<div class="pagination" style="width:100%;text-align: center">
		<?php if (isset($this->previous)): ?>
			<a href="<?= $this->url(array('page' => $this->first)); ?>">Start</a>
		<?php else: ?>
			<span class="disabled">Start</span>
		<?php endif; ?>

		<?php if (isset($this->previous)): ?>
			<a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; Previous</a>
		<?php else: ?>
			<span class="disabled">&lt; Previous</span>
		<?php endif; ?>

		<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
				<a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
			<?php else: ?>
				<?= $page; ?>
			<?php endif; ?>
		<?php endforeach; ?>

    	<?php if (isset($this->next)): ?>
			<a href="<?= $this->url(array('page' => $this->next)); ?>">Next &gt;</a>
		<?php else: ?>
			<span class="disabled">Next &gt;</span>
		<?php endif; ?>

		<?php if (isset($this->next)): ?>
			<a href="<?= $this->url(array('page' => $this->last)); ?>">End</a>
		<?php else: ?>
			<span class="disabled">End</span>
		<?php endif; ?>
		&nbsp; Page <?= $this->current; ?> of <?= $this->last; ?>

</div>
<?php }?>
