<?php 
/**
 * Copyright 2016 The President and Fellows of Harvard College
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */
if ($this->last > 0) {?>
<div class="pagination" style="width:100%;text-align: center">
		<?php if (isset($this->previous)): ?>
			<a href="<?= $this->url(array('page' => $this->first)); ?>">Start</a>
		<?php else: ?>
			<span class="disabled">Start</span>
		<?php endif; ?>

		<?php if (isset($this->previous)): ?>
			<a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; Previous</a>
		<?php else: ?>
			<span class="disabled">&lt; Previous</span>
		<?php endif; ?>

		<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
				<a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a>
			<?php else: ?>
				<?= $page; ?>
			<?php endif; ?>
		<?php endforeach; ?>

    	<?php if (isset($this->next)): ?>
			<a href="<?= $this->url(array('page' => $this->next)); ?>">Next &gt;</a>
		<?php else: ?>
			<span class="disabled">Next &gt;</span>
		<?php endif; ?>

		<?php if (isset($this->next)): ?>
			<a href="<?= $this->url(array('page' => $this->last)); ?>">End</a>
		<?php else: ?>
			<span class="disabled">End</span>
		<?php endif; ?>
		&nbsp; Page <?= $this->current; ?> of <?= $this->last; ?>

</div>
<?php }?>
